services:  
  inventoryservice_ps:
    build:
      context: ./inventoryservice_ps
    container_name: inventoryservice_ps_ct
    environment:
      - project_id=ada2025-450207
    ports:
      - "5000:5000"
      
  orderrecordservice_ps:
    build:
      context: ./orderrecordservice_ps
    container_name: orderrecordservice_ps_ct
    environment:
      - project_id=ada2025-450207
    ports:
      - "5001:5000"
      
      
